$ANSIBLE_VAULT;1.1;AES256
30383131663364326365363934663362303336303735643365333936616666376263313935383263
3635616662363564353331653561316263393337383130610a303938636138343461316433303334
30653532613230643031363136656262383538313931616663373730393934393130636564393462
3034326239313332650a316434383432613132313664363735356439336161643963646231323662
65393339303435633861333639373565636463326130323735636164653665623061646331366133
6133343839343562633833663339643234643432643230333762
